#!/usr/bin/env sh

sleep 30 
[ ! -d ~/.cache/transmission ] && mkdir -p ~/.cache/transmission

wget -P ~/.cache/transmission http://john.bitsurge.net/public/biglist.p2p.gz
gzip -d ~/.cache/transmission/biglist.p2p.gz

if [ -f ~/.config/transmission-daemon/blocklists/biglist.p2p ]; then
	rm ~/.config/transmission-daemon/blocklists/*
fi

mv ~/.cache/transmission/biglist.p2p ~/.config/transmission-daemon/blocklists/

[ -z "$(pgrep transmission)" ] && transmission-daemon &
